%ISOCUT4 - 
%
% Syntax:  [dipscore, cutpoint] = isocut4(samples)
%
% Inputs:
%    samples - double (1,N)
%
% Outputs:
%    dipscore - double (1,1)
%    cutpoint - double (1,1)
%
% Auto-generated by mcwrap: https://github.com/magland/mcwrap
